/**
 * Each mining hull's three fits, from research done on 29 September 2026 into what miners publish and fly since the
 * Catalyst expansion (18 November 2025, which added the destroyers and crits and made every laser cycle four times
 * faster): EVE Workbench's most-voted and newest fits per hull (votes and upload dates in each source), set against what
 * zKillboard's last 400 losses of each hull carried. EVE University was read too but is partly pre-Catalyst. Yields are
 * never written here: MasteryTiers works them out from ESI's dogma. Names are the game's exact spelling. The Rorqual and
 * the Perseverance have none: no fit published since Catalyst for the first, none popular for the second. Pure.
 */

import type { Tier } from './miningFits';

const ALL_V_YIELD: [string, number][] = [['Mining', 5], ['Astrogeology', 5], ['Mining Precision', 5], ['Mining Exploitation', 5]];
const HIGHWALL = "Inherent Implants 'Highwall' Mining MX-1005";
const MICHI = "Michi's Excavation Augmentor";

export const MASTERY: Record<number, Tier[]> = {
  // Venture
  32880: [
    {
      key: 'start', what: 'EP-S lasers cost what a Miner I does and mine 30% more; one upgrade, a small shield and an afterburner. It lives on its +2 warp core strength and quick align, not its tank.',
      high: [{ name: 'EP-S Gaussian Scoped Mining Laser', qty: 2 }],
      mid: [{ name: '1MN Y-S8 Compact Afterburner' }, { name: 'ML-3 Compact Mining Survey Chipset' }, { name: 'Medium Shield Extender I' }],
      low: [{ name: 'Mining Laser Upgrade I' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 2 }, { name: 'Small EM Shield Reinforcer I' }],
      drones: [{ name: 'Hobgoblin I', qty: 2 }],
      train: [['Mining Frigate', 3], ['Mining', 3]],
      source: 'EVE Workbench, “Full-Miner T1 2026 SafeZonesOnly” (8 March 2026, 13 up); the most-voted Venture fit (“Alpha miner and salvager”, 36 up) has the same core',
    },
    {
      key: 'solid', what: 'Tech II lasers and upgrade, and the Chipset II for crits. Fills its 5,000 m³ in about ten minutes.',
      high: [{ name: 'Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Monopropellant Enduring Afterburner' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 2 }, { name: 'Small EM Shield Reinforcer I' }],
      drones: [{ name: 'Hobgoblin II', qty: 2 }],
      train: [['Mining Frigate', 4], ['Mining', 4]],
      source: 'EVE Workbench, “Alpha T2 Best-Miner SafeZonesOnly 2026” (8 March 2026, 14 up) with the upgrade of “High-Yield Ore Endurance Venture”',
    },
    {
      key: 'max', what: 'As far as a Venture goes: the same fit with every yield and crit skill at V and a yield implant. The Pioneer mines about a third more for ~3 M, so this is where you move on.',
      high: [{ name: 'Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Afterburner II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 2 }, { name: 'Small EM Shield Reinforcer I' }],
      drones: [{ name: 'Hobgoblin II', qty: 2 }],
      implants: [HIGHWALL],
      train: [['Mining Frigate', 5], ...ALL_V_YIELD],
      source: 'the ceiling of the popular fits on EVE Workbench and zKillboard; the Pioneer step from forum yield comparisons (October and November 2025)',
    },
  ],
  // Venture Consortium Issue
  89648: [
    {
      key: 'start', what: 'The Venture’s fit with its fourth mid slot on a hardener. It mines like a Venture; what you pay for is crits half as often again, more hold and tank.',
      high: [{ name: 'EP-S Gaussian Scoped Mining Laser', qty: 2 }],
      mid: [{ name: '1MN Y-S8 Compact Afterburner' }, { name: 'ML-3 Compact Mining Survey Chipset' }, { name: 'Medium Shield Extender I' }, { name: 'Compact Multispectrum Shield Hardener' }],
      low: [{ name: 'Mining Laser Upgrade I' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 2 }, { name: 'Small EM Shield Reinforcer I' }],
      drones: [{ name: 'Hobgoblin I', qty: 2 }],
      train: [['Mining', 3]],
      source: 'the Venture’s starting fit (EVE Workbench) plus the hardener every Consortium Issue fit adds',
    },
    {
      key: 'solid', what: 'Tech II lasers, Chipset II, three shield rigs: about 9,700 EHP.',
      high: [{ name: 'Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Monopropellant Enduring Afterburner' }, { name: 'Medium Shield Extender II' }, { name: 'Compact Multispectrum Shield Hardener' }],
      low: [{ name: 'Mining Laser Upgrade II' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 3 }],
      drones: [{ name: 'Hobgoblin II', qty: 2 }],
      train: [['Mining Frigate', 4], ['Mining', 4]],
      source: 'EVE Workbench, “Venture Consortium Issue” (18 November 2025)',
    },
    {
      key: 'max', what: 'Every yield and crit skill at V and a yield implant. A ~3 M Pioneer still mines more; this one is for its warp strength and agility in risky space.',
      high: [{ name: 'Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Afterburner II' }, { name: 'Medium Shield Extender II' }, { name: 'Multispectrum Shield Hardener II' }],
      low: [{ name: 'Mining Laser Upgrade II' }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 3 }],
      drones: [{ name: 'Hobgoblin II', qty: 2 }],
      implants: [HIGHWALL],
      train: [['Mining Frigate', 5], ...ALL_V_YIELD],
      source: 'the Consortium Issue fits on EVE Workbench, with the skills and implant every hull’s top tier takes',
    },
  ],
  // Pioneer
  89240: [
    {
      key: 'start', what: 'Three lasers where the Venture has two, and a +50% role bonus: the first real step up. No warp core strength, so watch local.',
      high: [{ name: 'EP-S Gaussian Scoped Mining Laser', qty: 3 }],
      mid: [{ name: 'ML-3 Compact Mining Survey Chipset' }, { name: '1MN Y-S8 Compact Afterburner' }, { name: 'Medium Azeotropic Restrained Shield Extender' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 2 }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 3 }],
      drones: [{ name: 'Hobgoblin I', qty: 4 }],
      train: [['Mining', 4]],
      source: 'EVE Workbench, a Pioneer fit of 20 June 2026 and “Basic ORE Arc Pioneer” (28 June 2026)',
    },
    {
      key: 'solid', what: 'Tech II lasers and two upgrades, with processor rigs for the CPU they take.',
      high: [{ name: 'Miner II', qty: 3 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Y-S8 Compact Afterburner' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Small Processor Overclocking Unit I', qty: 2 }, { name: 'Small Core Defense Field Extender I' }],
      drones: [{ name: 'Hobgoblin II', qty: 4 }],
      train: [['Mining Destroyer', 3], ['Mining Upgrades', 4]],
      source: 'EVE Workbench, “Pioneer High-sec Max Yield” (19 May 2026); the most-voted Pioneer fit (“Danger - Alpha T2 Miner”, 8 up, 11 favourites) is the same with one upgrade',
    },
    {
      key: 'max', what: 'Modulated Deep Core Miners take crystals: Type B mines half as much again as Miner IIs, with residue (64% of cycles) as the price. Every yield skill at V.',
      high: [{ name: 'Modulated Deep Core Miner II', qty: 3 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Y-S8 Compact Afterburner' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Small Processor Overclocking Unit I', qty: 2 }, { name: 'Small Core Defense Field Extender I' }],
      drones: [{ name: 'Hobgoblin II', qty: 4 }],
      crystal: { kind: 'B II', spares: 3 },
      implants: [HIGHWALL],
      train: [['Mining Destroyer', 5], ...ALL_V_YIELD],
      source: 'the crystal option seen on EVE Workbench, with the skills and implant every hull’s top tier takes',
    },
  ],
  // Pioneer Consortium Issue
  89647: [
    {
      key: 'start', what: 'The Pioneer’s fit with a hardener in the fourth mid. More hold (10,000 m³), crits half as often again.',
      high: [{ name: 'EP-S Gaussian Scoped Mining Laser', qty: 3 }],
      mid: [{ name: 'ML-3 Compact Mining Survey Chipset' }, { name: '1MN Y-S8 Compact Afterburner' }, { name: 'Medium Azeotropic Restrained Shield Extender' }, { name: 'Compact Multispectrum Shield Hardener' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 2 }],
      rigs: [{ name: 'Small Core Defense Field Extender I', qty: 3 }],
      drones: [{ name: 'Hobgoblin I', qty: 4 }],
      train: [['Mining', 4]],
      source: 'the Pioneer’s starting fit plus the hardener the Consortium Issue fits add (EVE Workbench)',
    },
    {
      key: 'solid', what: 'Tech II lasers, two upgrades and about 10,700 EHP: the high-sec favourite among the small hulls.',
      high: [{ name: 'Miner II', qty: 3 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '1MN Monopropellant Enduring Afterburner' }, { name: 'Medium F-S9 Regolith Compact Shield Extender' }, { name: 'Compact Multispectrum Shield Hardener' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Small Processor Overclocking Unit I', qty: 2 }, { name: 'Small EM Shield Reinforcer I' }],
      drones: [{ name: 'Hobgoblin II', qty: 4 }],
      train: [['Mining Destroyer', 3], ['Mining Upgrades', 4]],
      source: 'EVE Workbench, “Defender” (19 November 2025); zKillboard: Miner II and Mining Laser Upgrade II on most of the last 400 lost',
    },
    {
      key: 'max', what: 'Three Modulated Deep Core Miners on Type B crystals, a proper shield tank, and drones for rats and more ore.',
      high: [{ name: 'Modulated Deep Core Miner II', qty: 3 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'Medium F-S9 Regolith Compact Shield Extender' }, { name: 'Compact EM Shield Hardener' }, { name: 'Enduring Multispectrum Shield Hardener' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Small Processor Overclocking Unit II' }, { name: 'Small Core Defense Field Extender I', qty: 2 }],
      drones: [{ name: 'Warrior II', qty: 4 }, { name: 'Mining Drone II', qty: 4 }],
      crystal: { kind: 'B II', spares: 3 },
      implants: [HIGHWALL],
      train: [['Mining Destroyer', 5], ...ALL_V_YIELD],
      source: 'EVE Workbench, “Fiko’s Max Yield - Modulated Miner” (21 May 2026)',
    },
  ],
  // Outrider
  89649: [
    {
      key: 'start', what: 'A booster and escape hull, not a yield step: it mines less than a Pioneer but boosts a small fleet and jumps it out with its Micro Jump Field Generator.',
      high: [{ name: 'Miner II', qty: 3 }, { name: 'Mining Foreman Burst I', charge: 'Mining Laser Optimization Charge' }],
      mid: [{ name: 'Micro Jump Field Generator' }, { name: 'ML-3 Compact Mining Survey Chipset' }, { name: 'Medium Shield Extender II' }, { name: 'Multispectrum Shield Hardener II' }, { name: '1MN Y-S8 Compact Afterburner' }],
      low: [{ name: 'Nanofiber Internal Structure II' }, { name: 'Inertial Stabilizers II' }, { name: 'Mining Laser Upgrade I' }],
      rigs: [{ name: 'Small Command Processor I' }, { name: 'Small Core Defense Field Extender I' }],
      drones: [{ name: 'Hobgoblin II', qty: 5 }],
      train: [['Mining Foreman', 1]],
      source: 'EVE Workbench Outrider fits of November 2025; zKillboard: the Micro Jump Field Generator and Mining Foreman Burst II on most of the last 400 lost',
    },
    {
      key: 'solid', what: 'Two tech II bursts: cycles shorter for everyone in range, and more crits and less residue from the Efficiency charge.',
      high: [{ name: 'Miner II', qty: 3 }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Efficiency Charge' }],
      mid: [{ name: 'Micro Jump Field Generator' }, { name: 'Mining Survey Chipset II' }, { name: 'Medium Shield Extender II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }],
      low: [{ name: 'Nanofiber Internal Structure II', qty: 3 }],
      rigs: [{ name: 'Small Command Processor I' }, { name: 'Small Core Defense Field Extender II' }],
      drones: [{ name: 'Hobgoblin II', qty: 5 }],
      train: [['Command Destroyers', 3], ['Mining Foreman', 5]],
      source: 'EVE Workbench, “Outrider - Demofitting” (18 November 2025) and “Outrider - Ori” (29 November 2025)',
    },
    {
      key: 'max', what: 'Modulated Deep Core Miners on crystals under two tech II bursts, with a warp core stabiliser: a booster that still mines.',
      high: [{ name: 'Modulated Deep Core Miner II', qty: 3 }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Field Enhancement Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }],
      mid: [{ name: '10MN Y-S8 Compact Afterburner' }, { name: 'Drone Navigation Computer I' }, { name: 'Mining Survey Chipset II' }, { name: 'Compact Multispectrum Shield Hardener' }, { name: 'Small Azeotropic Restrained Shield Extender' }],
      low: [{ name: 'Warp Core Stabilizer II' }, { name: 'Inertial Stabilizers II', qty: 2 }],
      rigs: [{ name: 'Small Processor Overclocking Unit I' }, { name: 'Small Command Processor I' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 3 },
      implants: [HIGHWALL],
      train: [['Command Destroyers', 5], ['Mining Director', 1], ...ALL_V_YIELD],
      source: 'EVE Workbench, “Loru’s Bulwark Mining Booster” (12 June 2026)',
    },
  ],
  // Prospect
  33697: [
    {
      key: 'start', what: 'Built for low-sec, null and wormholes: a covert ops cloak and a 12,500 m³ hold. Without Cloaking IV it’s a dear Venture; in high-sec it mines about half as much again as one for many times the price.',
      high: [{ name: 'Miner II', qty: 2 }, { name: 'Covert Ops Cloaking Device II' }],
      mid: [{ name: '1MN Y-S8 Compact Afterburner' }, { name: 'ML-3 Compact Mining Survey Chipset' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 3 }, { name: 'Inertial Stabilizers II' }],
      rigs: [{ name: 'Small Low Friction Nozzle Joints I', qty: 2 }],
      train: [['Cloaking', 4]],
      source: 'EVE Workbench Prospect fits (its engine computes none for this hull, so the yields here are the app’s)',
    },
    {
      key: 'solid', what: 'Three tech II upgrades and a cap recharger.',
      high: [{ name: 'Miner II', qty: 2 }, { name: 'Covert Ops Cloaking Device II' }],
      mid: [{ name: 'ML-3 Compact Mining Survey Chipset' }, { name: '1MN Y-S8 Compact Afterburner' }, { name: 'Eutectic Compact Cap Recharger' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }, { name: 'Inertial Stabilizers II' }],
      rigs: [{ name: 'Small Low Friction Nozzle Joints II' }, { name: 'Small EM Shield Reinforcer I' }],
      train: [['Expedition Frigates', 3], ['Mining Upgrades', 4]],
      source: 'EVE Workbench, “Ore prospect” (26 May 2026)',
    },
    {
      key: 'max', what: 'Modulated Deep Core Miners on crystals under the cloak; sub-3-second warp if you trade the stabiliser for the Inertial.',
      high: [{ name: 'Modulated Deep Core Miner II', qty: 2 }, { name: 'Covert Ops Cloaking Device II' }],
      mid: [{ name: '1MN Afterburner II' }, { name: 'Mining Survey Chipset II' }, { name: 'F-90 Compact Sensor Booster' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }, { name: 'Warp Core Stabilizer II' }],
      rigs: [{ name: 'Small Processor Overclocking Unit II' }, { name: 'Small Auxiliary Thrusters I' }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [HIGHWALL],
      train: [['Expedition Frigates', 5], ['Mining Frigate', 5], ...ALL_V_YIELD],
      source: 'EVE Workbench, “Max Mining Yield Sub-3 Warp” (10 favourites, 2021, before Catalyst) and “Loru’s Bulwark Miner” (12 June 2026)',
    },
  ],
  // Endurance
  37135: [
    {
      key: 'start', what: 'An ice frigate: one ice laser, a cloak, a 19,000 m³ hold. Ice belts are gank hunting grounds.',
      high: [{ name: 'Ice Mining Laser I' }, { name: 'Prototype Cloaking Device I' }],
      mid: [{ name: 'ML-3 Compact Mining Survey Chipset' }, { name: '5MN Y-T8 Compact Microwarpdrive' }, { name: 'Medium Shield Extender II' }, { name: 'Multispectrum Shield Hardener II' }],
      low: [{ name: 'Ice Harvester Upgrade I', qty: 3 }],
      rigs: [{ name: 'Small Low Friction Nozzle Joints I', qty: 2 }],
      train: [['Ice Harvesting', 1]],
      source: 'EVE Workbench Endurance ice fits; zKillboard: Ice Mining Laser II, Ice Harvester Upgrade II and Chipset II common on the last 400 lost',
    },
    {
      key: 'solid', what: 'The tech II ice laser and upgrades: about a block every 48 seconds at all V.',
      high: [{ name: 'Ice Mining Laser II' }, { name: 'Prototype Cloaking Device I' }, { name: 'Core Probe Launcher I' }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '5MN Y-T8 Compact Microwarpdrive' }, { name: 'Multispectrum Shield Hardener II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Ice Harvester Upgrade II', qty: 3 }],
      rigs: [{ name: 'Small Low Friction Nozzle Joints II', qty: 2 }],
      drones: [{ name: 'Hornet II', qty: 3 }],
      train: [['Expedition Frigates', 3]],
      source: 'EVE Workbench, “Ice Endurance” and “Winter Nexus 2025 miner” (11 December 2025, 26 May 2026); the most-voted “Endurance WH Ice” (8 up) has the same core',
    },
    {
      key: 'max', what: 'The ORE ice laser (no residue) and the Yeti ice implant, every ice skill at V.',
      high: [{ name: 'ORE Ice Mining Laser' }, { name: 'Prototype Cloaking Device I' }, { name: 'Core Probe Launcher I' }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: '5MN Y-T8 Compact Microwarpdrive' }, { name: 'Multispectrum Shield Hardener II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Ice Harvester Upgrade II', qty: 3 }],
      rigs: [{ name: 'Small Low Friction Nozzle Joints II', qty: 2 }],
      drones: [{ name: 'Hornet II', qty: 3 }],
      implants: ["Inherent Implants 'Yeti' Ice Harvesting IH-1005"],
      train: [['Ice Harvesting', 5], ['Mining Frigate', 5], ['Expedition Frigates', 5], ['Mining Precision', 5], ['Mining Exploitation', 5]],
      source: 'EVE Workbench ice fits with the ORE laser; the Yeti implant from the research into yield implants',
    },
  ],
  // Procurer
  17480: [
    {
      key: 'start', what: 'The barge that survives: about 50,000 EHP on minimal skills, the least yield of the three barges.',
      high: [{ name: 'Strip Miner I', qty: 2 }],
      mid: [{ name: 'Medium Shield Extender I' }, { name: 'Multispectrum Shield Hardener I' }, { name: 'ML-3 Compact Mining Survey Chipset' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 3 }],
      rigs: [{ name: 'Medium Core Defense Field Extender I', qty: 2 }, { name: 'Medium EM Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      train: [['Mining Barge', 1]],
      source: 'EVE Workbench, “Highsec Fleet - Minimal Skills” (16 July and 31 August 2026)',
    },
    {
      key: 'solid', what: 'Modulated Strip Miners on Type A crystals and a Damage Control: tank first, yield second.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Core Defense Field Extender II', qty: 2 }, { name: 'Medium EM Shield Reinforcer II' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Mining Barge', 3]],
      source: 'EVE Workbench, “Low-Sec Tank” (14 March 2026, 88,000 EHP); the most-voted Procurer fit (“Mining * ORE * ANTIGANG”) has the same shape',
    },
    {
      key: 'max', what: 'Type B crystals and a yield implant. The next step with the same job is the Skiff, with about twice the EHP.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Core Defense Field Extender II', qty: 2 }, { name: 'Medium EM Shield Reinforcer II' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [HIGHWALL],
      train: [['Mining Barge', 5], ...ALL_V_YIELD],
      source: 'the solid fit with the crystals, skills and implant every top tier takes',
    },
  ],
  // Retriever
  17478: [
    {
      key: 'start', what: 'The hold barge: 27,500 m³ (more with skill), so fewer trips when you mine alone. Only two mid slots, so a thin tank.',
      high: [{ name: 'Strip Miner I', qty: 2 }],
      mid: [{ name: 'Enduring Multispectrum Shield Hardener' }, { name: 'ML-3 Compact Mining Survey Chipset' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium Drone Mining Augmentor I' }, { name: 'Medium EM Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      train: [['Mining Barge', 1]],
      source: 'EVE Workbench, “Loru’s HS - Solo Ore Newbro” (5 January 2026, 5 up, 18 favourites), with tech I upgrades until Mining Upgrades IV',
    },
    {
      key: 'solid', what: 'Modulated Strip Miners on Type A crystals and three tech II upgrades.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II' }, { name: 'Mining Survey Chipset II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium EM Shield Reinforcer I' }, { name: 'Medium Thermal Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Mining Barge', 3]],
      source: 'EVE Workbench, “EUNI ORE Retriever T2” (2 August 2026) and “Retriever T2” (27 April 2026)',
    },
    {
      key: 'max', what: 'Type B crystals, the ones most loaded on Retrievers lost lately, and a yield implant. Swap an upgrade for a Damage Control II if gankers are about.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II' }, { name: 'Mining Survey Chipset II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium EM Shield Reinforcer I' }, { name: 'Medium Thermal Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [HIGHWALL],
      train: [['Mining Barge', 5], ...ALL_V_YIELD],
      source: 'zKillboard (the crystals on the last 400 Retrievers lost) on the solid fit, with the skills and implant every top tier takes',
    },
  ],
  // Covetor
  17476: [
    {
      key: 'start', what: 'The yield barge: most m³ of the three, a 9,000 m³ hold that fills in minutes, and no tank to speak of. A fleet ship, with a hauler or an Orca.',
      high: [{ name: 'Strip Miner I', qty: 2 }],
      mid: [{ name: 'Compact EM Shield Amplifier' }, { name: 'ML-3 Compact Mining Survey Chipset' }],
      low: [{ name: 'Mining Laser Upgrade I', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium Core Defense Field Extender I' }, { name: 'Medium EM Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      train: [['Mining Barge', 1]],
      source: 'EVE Workbench, “Loru’s HS - Ore/Moon Miner” (12 May 2026)',
    },
    {
      key: 'solid', what: 'Modulated Strip Miners on Type A crystals and three tech II upgrades.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II' }, { name: 'Mining Survey Chipset II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium Core Defense Field Extender I', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Mining Barge', 3]],
      source: 'the common Covetor fit on EVE Workbench and on zKillboard’s last 400 lost',
    },
    {
      key: 'max', what: 'Type B crystals and a yield implant. EVE University: no Covetor fit tanks a gank in 0.5 even at all V, so it mines where it’s watched.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II' }, { name: 'Mining Survey Chipset II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium Core Defense Field Extender I', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [HIGHWALL],
      train: [['Mining Barge', 5], ...ALL_V_YIELD],
      source: 'the solid fit with the crystals, skills and implant every top tier takes; EVE University’s Covetor page (August 2025)',
    },
  ],
  // Skiff
  22546: [
    {
      key: 'start', what: 'The exhumer that holds against small high-sec ganks: five mid slots of shield. The least yield of the three exhumers.',
      high: [{ name: 'Strip Miner I', qty: 2 }],
      mid: [{ name: 'ML-3 Compact Mining Survey Chipset' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Medium Shield Extender II' }, { name: '10MN Y-S8 Compact Afterburner' }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Core Defense Field Extender I', qty: 2 }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      train: [['Exhumers', 1]],
      source: 'EVE Workbench Skiff fits; zKillboard: Multispectrum Shield Hardener II and Damage Control II on most of the last 400 lost',
    },
    {
      key: 'solid', what: 'Modulated Strip Miners on Type A crystals behind a Large Shield Extender: about 120,000 EHP.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Large Shield Extender II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: '10MN Afterburner II' }, { name: 'Mining Survey Chipset II' }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Core Defense Field Extender II', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Exhumers', 3]],
      source: 'EVE Workbench, “ORE - Type A Only” (3 May 2026)',
    },
    {
      key: 'max', what: 'Type B crystals and three upgrades. Richer pilots fit two ORE Strip Miners instead (about 189 M each): less yield, no residue, no crystals to swap.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'EM Shield Hardener II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Republic Fleet Medium Shield Extender' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Core Defense Field Extender II', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [HIGHWALL],
      train: [['Exhumers', 5], ...ALL_V_YIELD],
      source: 'EVE Workbench, “HardRocks” (8 up, 2019) for the tank, with Type B crystals in place of its ORE Strip Miners',
    },
  ],
  // Mackinaw
  22548: [
    {
      key: 'start', what: 'The hold exhumer: 31,500 m³ and more with skill, for long runs between trips. Long unattended runs are exactly when ganks land.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Large F-S9 Regolith Compact Shield Extender' }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Core Defense Field Extender II', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Exhumers', 1]],
      source: 'EVE Workbench, “Rock Slayer T2 ORE/Moon” (5 up, 2022); Strip Miner I is fine while crystal skills lag',
    },
    {
      key: 'solid', what: 'Type B crystals and three upgrades: more yield, thinner tank (about 55,000 EHP).',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Mining Survey Chipset II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit II' }, { name: 'Medium Core Defense Field Extender II' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      train: [['Exhumers', 3]],
      source: 'EVE Workbench, “Fiko’s Max Yield - Default Build (Solo)” (21 May 2026)',
    },
    {
      key: 'max', what: 'Two ORE Strip Miners: less per minute than Type B crystals, but no residue and no crystals to burn out, which is what a long unattended run wants. The most-voted Mackinaw fit.',
      high: [{ name: 'ORE Strip Miner', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II' }, { name: 'Mining Survey Chipset II' }, { name: 'Thermal Shield Amplifier II' }, { name: 'EM Shield Amplifier II' }],
      low: [{ name: 'Damage Control II' }, { name: 'Mining Laser Upgrade II', qty: 2 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit II' }, { name: 'Medium Core Defense Field Extender II' }],
      drones: [{ name: 'Hobgoblin II', qty: 5 }, { name: 'Mining Drone II', qty: 5 }],
      implants: [HIGHWALL],
      train: [['Exhumers', 5], ...ALL_V_YIELD],
      source: 'EVE Workbench, “Mack Solo Miner” (8 up, 2019) and “Balanced Yield/Tank” (27 September 2026)',
    },
  ],
  // Hulk
  22544: [
    {
      key: 'start', what: 'The yield exhumer: the most m³ of any ship that mines, an 11,500 m³ hold, and under 25,000 EHP. It wants an Orca or a hauler, and a watched system.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Mining Survey Chipset II' }, { name: 'Multispectrum Shield Hardener II' }, { name: 'Compact Multispectrum Shield Hardener' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit I' }, { name: 'Medium Core Defense Field Extender I' }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      crystal: { kind: 'A II', spares: 2 },
      train: [['Exhumers', 1]],
      source: 'EVE Workbench Hulk fits; zKillboard: Mining Laser Upgrade II on 315 of the last 400 lost',
    },
    {
      key: 'solid', what: 'Type B crystals: fills its hold in about four minutes.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Mining Survey Chipset II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit II' }, { name: 'Medium Core Defense Field Extender II' }],
      drones: [{ name: 'Warrior II', qty: 5 }, { name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      train: [['Exhumers', 3]],
      source: 'EVE Workbench, “Fiko’s Max Yield - Default Build” (21 May 2026)',
    },
    {
      key: 'max', what: 'Both yield implants and every skill at V. Boosts are the rest: a published table (January 2022) puts an Orca’s at about two thirds more again.',
      high: [{ name: 'Modulated Strip Miner II', qty: 2 }],
      mid: [{ name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Mining Survey Chipset II' }, { name: 'Medium Shield Extender II' }],
      low: [{ name: 'Mining Laser Upgrade II', qty: 3 }],
      rigs: [{ name: 'Medium Processor Overclocking Unit II' }, { name: 'Medium Core Defense Field Extender II' }],
      drones: [{ name: 'Warrior II', qty: 5 }, { name: 'Mining Drone II', qty: 5 }],
      crystal: { kind: 'B II', spares: 2 },
      implants: [MICHI, HIGHWALL],
      train: [['Exhumers', 5], ...ALL_V_YIELD],
      source: 'the solid fit with both implants; boost figures from github.com/Wilm0rien/EveOnlineMiningYield (January 2022)',
    },
  ],
  // Porpoise
  42244: [
    {
      key: 'start', what: 'Boosts a small fleet and compresses its ore on the spot; 50,000 m³ ore hold. The industrial core stops the ship dead for its whole cycle and burns Heavy Water.',
      high: [{ name: 'Mining Foreman Burst I', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst I', charge: 'Mining Laser Field Enhancement Charge' }, { name: 'Medium Industrial Core I' }, { name: 'Medium Asteroid Ore Compressor I' }],
      mid: [{ name: 'Large Shield Extender II', qty: 2 }, { name: 'Multispectrum Shield Hardener II', qty: 2 }],
      low: [{ name: 'Damage Control II' }, { name: 'Reinforced Bulkheads II' }],
      rigs: [{ name: 'Medium Core Defense Field Extender I', qty: 2 }, { name: 'Medium EM Shield Reinforcer I' }],
      drones: [{ name: 'Mining Drone I', qty: 5 }],
      train: [['Mining Foreman', 1], ['Industrial Reconfiguration', 1], ['Shipboard Compression Technology', 1]],
      source: 'EVE Workbench, “Raqa’s Build” (21 May 2026)',
    },
    {
      key: 'solid', what: 'Tech II bursts and core, drone mining augmentors, and an MWD to reposition.',
      high: [{ name: 'Medium Industrial Core II' }, { name: 'Medium Asteroid Ore Compressor I' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Field Enhancement Charge' }],
      mid: [{ name: 'Drone Navigation Computer II' }, { name: 'Large Shield Extender II' }, { name: 'Multispectrum Shield Hardener II' }, { name: '50MN Quad LiF Restrained Microwarpdrive' }],
      low: [{ name: 'Inertial Stabilizers II', qty: 2 }],
      rigs: [{ name: 'Medium Polycarbon Engine Housing I' }, { name: 'Medium Drone Mining Augmentor II', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      train: [['Mining Foreman', 5], ['Mining Director', 1], ['Industrial Reconfiguration', 5]],
      source: 'EVE Workbench, “Loru’s HS - Ore Border Compressor” (12 May 2026, 6 favourites)',
    },
    {
      key: 'max', what: 'The Efficiency charge on the second burst (more crits, less residue for everyone) and a mindlink.',
      high: [{ name: 'Medium Industrial Core II' }, { name: 'Medium Asteroid Ore Compressor I' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Efficiency Charge' }],
      mid: [{ name: 'Drone Navigation Computer II' }, { name: 'Large Shield Extender II' }, { name: 'Multispectrum Shield Hardener II' }, { name: '50MN Quad LiF Restrained Microwarpdrive' }],
      low: [{ name: 'Inertial Stabilizers II', qty: 2 }],
      rigs: [{ name: 'Medium Polycarbon Engine Housing I' }, { name: 'Medium Drone Mining Augmentor II', qty: 2 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      implants: ['Mining Foreman Mindlink'],
      train: [['Industrial Command Ships', 5], ['Mining Director', 5], ['Industrial Reconfiguration', 5]],
      source: 'the solid fit with zKillboard’s most-used second charge (Efficiency, on 191 of the last 400 lost)',
    },
  ],
  // Orca
  28606: [
    {
      key: 'start', what: 'Bigger boosts, a 150,000 m³ ore hold and a 40,000 m³ fleet hangar, compression of everything: a multibox fleet’s mothership. A 1.2 B hull is a gank target, so tank first.',
      high: [{ name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Field Enhancement Charge' }, { name: 'Shield Command Burst I', charge: 'Shield Extension Charge' }, { name: 'Large Industrial Core I' }, { name: 'Large Asteroid Ore Compressor I' }],
      mid: [{ name: 'Large Shield Extender II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'EM Shield Amplifier II' }, { name: 'Thermal Shield Amplifier II' }],
      low: [{ name: 'Damage Control II' }, { name: 'Reinforced Bulkheads II' }],
      rigs: [{ name: 'Large Core Defense Field Extender I', qty: 3 }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      train: [['Mining Foreman', 5], ['Industrial Reconfiguration', 1]],
      source: 'the common Orca fits on EVE Workbench and zKillboard’s last 400 lost',
    },
    {
      key: 'solid', what: 'The tech II core, a cloak for moving it, and transverse bulkheads: about 459,000 EHP.',
      high: [{ name: 'Shield Command Burst II', charge: 'Shield Extension Charge' }, { name: 'Large Asteroid Ore Compressor I' }, { name: 'Large Industrial Core II' }, { name: 'Improved Cloaking Device II' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Field Enhancement Charge' }],
      mid: [{ name: 'Large Shield Extender II' }, { name: 'Multispectrum Shield Hardener II', qty: 2 }, { name: 'Thermal Shield Amplifier II' }, { name: 'EM Shield Amplifier II' }],
      low: [{ name: 'Damage Control II' }, { name: 'Reinforced Bulkheads II' }],
      rigs: [{ name: 'Large Transverse Bulkhead II', qty: 2 }, { name: 'Large Drone Mining Augmentor II' }],
      drones: [{ name: 'Mining Drone II', qty: 5 }],
      train: [['Industrial Reconfiguration', 5], ['Mining Director', 1]],
      source: 'EVE Workbench, “Loru’s HS Ore/Ice Fleet Compressor” (12 May 2026)',
    },
    {
      key: 'max', what: 'Three foreman bursts with all the charges that matter, faction tank, and the ORE Mining Director mindlink.',
      high: [{ name: 'Mining Foreman Burst II', charge: 'Mining Laser Optimization Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Field Enhancement Charge' }, { name: 'Mining Foreman Burst II', charge: 'Mining Laser Efficiency Charge' }, { name: 'Shield Command Burst II', charge: 'Shield Extension Charge' }, { name: 'Large Industrial Core II' }, { name: 'Large Asteroid Ore Compressor I' }],
      mid: [{ name: '100MN Afterburner II' }, { name: 'Caldari Navy Large Shield Extender' }, { name: 'Multispectrum Shield Hardener II' }, { name: 'Domination EM Shield Hardener' }, { name: 'Sentient Drone Navigation Computer' }],
      low: [{ name: 'Reinforced Bulkheads II' }, { name: 'Damage Control II' }],
      rigs: [{ name: 'Large Command Processor I' }, { name: 'Large Drone Mining Augmentor I' }, { name: 'Large Drone Mining Augmentor II' }],
      drones: [{ name: "'Augmented' Mining Drone", qty: 5 }],
      implants: ['ORE Mining Director Mindlink'],
      train: [['Industrial Command Ships', 5], ['Mining Director', 5], ['Industrial Reconfiguration', 5]],
      source: 'EVE Workbench, “Orca Multi” (18 August 2026)',
    },
  ],
};
