// Alpha's skill limits, from CCP's static data (SDE): ESI has no clone-state field and no list of what an Alpha can
// use. Run after a game update changes them:
//
//   curl -sS https://developers.eveonline.com/static-data/tranquility/latest.jsonl      # its buildNumber
//   curl -sSO https://developers.eveonline.com/static-data/tranquility/eve-online-static-data-<build>-jsonl.zip
//   unzip the archive's cloneGrades.jsonl, then
//   node scripts/alpha-caps.mjs <path to cloneGrades.jsonl> <build>
//
// Writes src/lib/alphaCaps.ts. The file has one grade a race (Caldari, Minmatar, Amarr, Gallente); on build 3561556
// (30 September 2026) all four list the same 175 skills at the same levels, and this stops if that ever changes,
// since the app keeps one cap a skill.
import fs from 'node:fs';

const [file, build] = process.argv.slice(2);
if (!file || !build) { console.error('usage: node scripts/alpha-caps.mjs <cloneGrades.jsonl> <build>'); process.exit(1); }

const grades = fs.readFileSync(file, 'utf8').split('\n').filter((l) => l.trim()).map((l) => JSON.parse(l));
const caps = new Map();
for (const g of grades) {
  for (const s of g.skills ?? []) {
    if (caps.has(s.typeID) && caps.get(s.typeID) !== s.level) { console.error(`The grades disagree on skill ${s.typeID}: ${caps.get(s.typeID)} and ${s.level}`); process.exit(1); }
    caps.set(s.typeID, s.level);
  }
}
const ids = [...caps.keys()].sort((a, b) => a - b);
const lines = [];
for (let i = 0; i < ids.length; i += 10) lines.push('  ' + ids.slice(i, i + 10).map((id) => `${id}: ${caps.get(id)},`).join(' '));
fs.writeFileSync(new URL('../src/lib/alphaCaps.ts', import.meta.url), `// Generated by scripts/alpha-caps.mjs from CCP's static data (cloneGrades.jsonl). Don't edit by hand.

/** The static data build these came from. */
export const ALPHA_CAPS_BUILD = ${Number(build)};

/**
 * The highest level of each skill an Alpha clone can use, by skill type ID. A skill not listed can't be used by an
 * Alpha at all (cap 0). Levels trained above a cap stay trained and go inactive while the account is Alpha.
 */
export const ALPHA_SKILL_CAPS: Record<number, number> = {
${lines.join('\n')}
};
`);
console.log(`${ids.length} skills from ${grades.length} grades`);
